### PR TITLE
Fix Scheduling Bugs & Improve Efficiency

### LINKED ISSUE #31: Scheduled for multiple courses at the same time
Peer teachers can be scheduled for multiple courses during the same time. Shane says this is because availability isn't updated after a PT is assigned a course (https://discord.com/channels/935939644363796490/945449460480213002/957743033019936818)

### PR DESCRIPTION
**Pull request by dantebarbieri**

### CODE REVIEW

**Comment by dantebarbieri** [comment]
Pretty sure the bug is fixed because I now require the person to still be available for a section, given what they've already been assigned to. Also with a high enough capacity for each section, everyone gets scheduled except people who cannot be scheduled at all. As an interesting side note, if a person's availability score is not positive, they cannot be scheduled.

## Fixes
- [x] People cannot be scheduled to multiple simultaneous labs anymore
- [x] People cannot be scheduled to ONLINE ONLINE labs anymore (this was a previously undiscovered problem)
- [x] Preference data is more accurately utilized during scheduling than it was before
- [x] Almost everything is a lot faster because we now use `HashMap` lookups instead of linear `ArrayList` searches where possible

## Possible Improvements
- [ ] Some things are still slow with regard to loops
- [ ] I don't have any direct testing which proves the fix for simultaneous schedules works

File: lambda/postSchedulePeerTeachers/Scheduler/src/main/java/db/Person.java [hunk 1]
```diff
@@ -115,18 +118,17 @@ public float getAvailabilityScore() {
     }
 
     public int getCurrentAssignments() {
-        return currentAssignments;
+        return sections.size();
     }
```
Comment (benbeauchamp7) [inline lambda/postSchedulePeerTeachers/Scheduler/src/main/java/db/Person.java]: This function name feels like it would return the actual assignments themselves rather than sections.size(), it could probably be named better

Comment (benbeauchamp7) [reply lambda/postSchedulePeerTeachers/Scheduler/src/main/java/db/Person.java]: Maybe getCurrentAssignmentsCount() or something

File: lambda/postSchedulePeerTeachers/Scheduler/src/main/java/db/Person.java [hunk 2]
```diff
@@ -115,18 +118,17 @@ public float getAvailabilityScore() {
...
     
-    public void addCurrentAssignment() {
-        currentAssignments++;
+    public void addCurrentAssignment(Section section) {
+        sections.put(section.getSectionId(), section);
     }
```
Comment (benbeauchamp7) [inline lambda/postSchedulePeerTeachers/Scheduler/src/main/java/db/Person.java]: Gonna harp on naming again- is sections a list of sections or specific assignments?

File: lambda/postSchedulePeerTeachers/Scheduler/src/main/java/db/Person.java [hunk 3]
```diff
@@ -160,13 +161,34 @@ public boolean isGoodSection(int sectionId, Section section) {
         return isQualified(section.getCourseId()) && isAvailable(section.getMeetings()) && !getPreferenceEquals(sectionId, DBPreference.CANT_DO);
     }
 
+    public boolean alreadyAssigned(String weekday, Time start, Time end) {
+        for (Section section : sections.values()) {
+            for (Meeting meeting : section.getMeetings()) {
+                if (weekday.equals(meeting.getWeekday()) && !(meeting.getStartTime().after(end) || meeting.getEndTime().before(start))) {
```
Comment (benbeauchamp7) [inline lambda/postSchedulePeerTeachers/Scheduler/src/main/java/db/Person.java]: I don't know Java enough to know if this can be sped up. If this function is called a bunch though, I'd look into it

File: lambda/postSchedulePeerTeachers/Scheduler/src/main/java/db/Section.java [hunk 4]
```diff
@@ -23,6 +26,10 @@ public Section(int courseId, String sectionNumber, int capacityPTs, int capacity
         currentTAs = 0;
     }
 
+    public int getSectionId() {
+        return sectionId;
+    }
+
     public int getCourseId() {
         return courseId;
     }
```
Comment (benbeauchamp7) [inline lambda/postSchedulePeerTeachers/Scheduler/src/main/java/db/Section.java:35]: Does Java do a thing that generates getters for you?

File: lambda/postSchedulePeerTeachers/Scheduler/src/main/java/scheduler/Handler.java [hunk 5]
```diff
@@ -58,13 +57,14 @@ public APIGatewayProxyResponseEvent handleRequest(final APIGatewayProxyRequestEv
...
-        GetParameterResponse parameterResult = ssmclient.getParameter(parameterRequest);
-        String dbpassword = parameterResult.parameter().value();
+        // GetParameterRequest parameterRequest = GetParameterRequest.builder()
+        //         .name("/tias/prod/db-password")
+        //         .withDecryption(true)
+        //         .build();
+        // SsmClient ssmclient = SsmClient.create();
+        // GetParameterResponse parameterResult = ssmclient.getParameter(parameterRequest);
+        // String dbpassword = parameterResult.parameter().value();
+        String dbpassword = "admin";
```
Comment (benbeauchamp7) [inline lambda/postSchedulePeerTeachers/Scheduler/src/main/java/scheduler/Handler.java]: Does this need to be reverted back so it works when you upload it? It looks like this might be for testing?

File: lambda/postSchedulePeerTeachers/Scheduler/src/main/java/scheduler/Handler.java [hunk 6]
```diff
@@ -304,33 +307,49 @@ static void schedulePeopleToSections() {
...
+                            if (frontPerson.alreadyAssigned(meeting.getWeekday(), meeting.getStartTime(), meeting.getEndTime())) {
+                                alreadyAssigned = true;
+                            }
+                        }
+                        if (!alreadyAssigned) {
+                            section.addAssignedPTs();
+                            frontPerson.addCurrentAssignment(section);
+                            schedule.putIfAbsent(preference.getSectionId(), new ArrayList<>());
+                            schedule.get(preference.getSectionId()).add(frontPerson.getPersonId());
+                        }
```
Comment (benbeauchamp7) [inline lambda/postSchedulePeerTeachers/Scheduler/src/main/java/scheduler/Handler.java]: This is repeated a few lines down- can it be stuck in a lambda? Does Java have lambdas? Anon functions? Idk

File: lambda/postSchedulePeerTeachers/Scheduler/src/main/java/scheduler/Handler.java [hunk 7]
```diff
@@ -304,33 +307,49 @@ static void schedulePeopleToSections() {
...
+                            if (frontPerson.alreadyAssigned(meeting.getWeekday(), meeting.getStartTime(), meeting.getEndTime())) {
+                                alreadyAssigned = true;
+                            }
+                        }
+                        if (!alreadyAssigned) {
+                            section.addAssignedPTs();
+                            frontPerson.addCurrentAssignment(section);
+                            schedule.putIfAbsent(sectionId, new ArrayList<>());
+                            schedule.get(sectionId).add(frontPerson.getPersonId());
+                        }
```
Comment (benbeauchamp7) [inline lambda/postSchedulePeerTeachers/Scheduler/src/main/java/scheduler/Handler.java]: See above

File: lambda/postSchedulePeerTeachers/Scheduler/src/main/java/scheduler/Handler.java [hunk 8]
```diff
@@ -341,10 +360,18 @@ static void schedulePeopleToSections() {
...
```
Comment (benbeauchamp7) [inline lambda/postSchedulePeerTeachers/Scheduler/src/main/java/scheduler/Handler.java]: Repeated again (would make a good anon function!)

**Review by benbeauchamp7 — CHANGES_REQUESTED** [review]
Lines 60-67 are commented in Handler.java. Be sure that they are supposed to be commented before making it onto the cloud. Otherwise, looks great!

File: lambda/postSchedulePeerTeachers/Scheduler/src/main/java/db/Person.java (hunk 3 above)
Comment (benbeauchamp7) [reply lambda/postSchedulePeerTeachers/Scheduler/src/main/java/db/Person.java]: https://stackoverflow.com/questions/47658552/how-to-find-any-element-in-a-hashmap-where-a-given-condition-about-that-element ??

Comment (dantebarbieri) [reply lambda/postSchedulePeerTeachers/Scheduler/src/main/java/db/Person.java]: The link that you sent cannot optimize the function further. There is no way (with the current design) to speedup the function, but it is actually not as slow as it would seem.

File: lambda/postSchedulePeerTeachers/Scheduler/src/main/java/db/Section.java (hunk 4 above)
Comment (dantebarbieri) [reply lambda/postSchedulePeerTeachers/Scheduler/src/main/java/db/Section.java:35]: Yes.

**Comment by dantebarbieri** [comment]
I've addressed the comments you left for me @benbeauchamp7. I'd appreciate you reviewing again and if you like it, approving the changes.

**Review by benbeauchamp7 — APPROVED** [review]
Looks great! I'm excited to see what the schedules will look like out of it

File: lambda/postSchedulePeerTeachers/Scheduler/src/main/java/db/Section.java (hunk 4 above)
Comment (benbeauchamp7) [reply lambda/postSchedulePeerTeachers/Scheduler/src/main/java/db/Section.java:35]: lol
