### PR TITLE
Fix Trade Requests Time Conflict Possibility

### LINKED ISSUE #87: Trade Requests Violate Time
⏳

### PR DESCRIPTION
**Pull request by dantebarbieri**
Closes #87

### CODE REVIEW

File: lambda/postTradeRequest/index.js [hunk 1]
```diff
@@ -88,6 +90,17 @@ exports.handler = async (event) => {
         helper_functions.GenerateErrorResponseAndLog({stack: ""}, response, "The requested course is not viable.")
         return response;
     }
+    
+    for (let meeting of requested_meetings) {
+        const conflictingSections = await helper_functions.queryDB(`SELECT section_meeting.* FROM section_assignment JOIN section_meeting ON section_assignment.section_id = section_meeting.section_id AND section_assignment.section_id != \$5 WHERE person_id = \$1 AND weekday = \$2 AND NOT (end_time < \$3 OR start_time > \$4)`, [requester_id, meeting.weekday, meeting.start_time, meeting.end_time, offered_id]).catch(err => helper_functions.GenerateErrorResponseAndLog(err, response, "Failed to get the requested section."))
+     
+        console.log(conflictingSections)
```
Comment (dantebarbieri) [inline lambda/postTradeRequest/index.js]:
```suggestion
        console.log('conflicting:', conflictingSections)
```

**Review by benbeauchamp7 — APPROVED** [review]
Good fix!
