### PR TITLE
Admin page and a chunk of labswap

### LINKED ISSUE #23: Assign User Roles
On sign-in, users should be directed to set their roles:

- Peer Teacher
- Teaching Assistant

These roles should be changeable on the profile page.

As far as Administrators and Professors, there must be a system for existing Administrators to nominate new ones. I am not sure how to handle Professors. This may be part of the scope that is cut, especially because Professors and TAs are more likely to be cut.

### LINKED ISSUE #63: Admin Page
pls

### LINKED ISSUE #70: Change all URL components to be lowercase in order to follow convention.
e.g.,
image

To follow convention, let us make sure all routes are lowercase such that the URL remains wholly lowercase.

### LINKED ISSUE #75: If a Day of the Week has No Labs, it all goes to Pot
Fall 2022 has no Friday labs at all for the courses we manage. As such, the app crashes, not understanding how this is possible.

Do we wish to leave the Friday column blank or should we remove it?

Regardless, we need to fix the breaking behavior. Pls

### PR DESCRIPTION
**Pull request by benbeauchamp7**
This pull request holds the admin page and all of it's functionality as well as some parts of the labswap page which is not complete yet. From the admin page, an administrator can

* Pre-register a new user
* Update user roles
* Delete users, protected with an alert guard
* Add courses
* Delete courses, protected with a text guard
* Export the schedule as a CSV
* Initiate changeover for the start of a new semester.

### CODE REVIEW

File: src/Components/Admin/AdminCourseList.tsx [hunk 1]
```diff
@@ -0,0 +1,129 @@
...
+      if (ref.current && !ref.current.contains(event.target) && showMenu) {
+        setShowMenu(false);
+      }
+    };
+
+    document.addEventListener('click', handleClickOutside, true);
+    return () => {
+      document.removeEventListener('click', handleClickOutside, true);
+    };
+  });
```
Comment (benbeauchamp7) [inline src/Components/Admin/AdminCourseList.tsx:26]: I'd love to make a component that does this

**Review by dantebarbieri — CHANGES_REQUESTED** [review]
All looks good except for adding new users. The submit button needs to be more visible. In Edge, I get a thin sliver of green (which is clickable):
image
And in Firefox, I get nothing at all:
image
This is despite the component appearing in the DOM when I go to the Elements Pane of the Inspector.

Everything else on the page works well, but these buttons have very different styling. Is that intentional? They look a little discordant.
image

**Review by dantebarbieri — APPROVED** [review]
tnx 4 fix
